// Renders docs/tools.md from the tool definitions so the schema the LLM sees and the docs never drift.
// `--check` exits 1 when the committed file is stale (used by CI).
import fs from 'node:fs';
import path from 'node:path';
import { z } from 'zod';
import { tools } from '../src/tools/index.js';

interface JsonSchema {
  type?: string;
  properties?: Record<string, JsonSchemaProp>;
  required?: string[];
}
interface JsonSchemaProp {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  default?: unknown;
  const?: unknown;
  anyOf?: JsonSchemaProp[];
  items?: JsonSchemaProp;
  minimum?: number;
  maximum?: number;
  format?: string;
}

function typeOf(p: JsonSchemaProp): string {
  if (p.enum) return p.enum.map((v) => JSON.stringify(v)).join(' \\| ');
  if (p.const !== undefined) return JSON.stringify(p.const);
  if (p.anyOf) return p.anyOf.map(typeOf).join(' \\| ');
  if (p.type === 'array') return `${p.items ? typeOf(p.items) : 'unknown'}[]`;
  if (p.format === 'uri') return 'url';
  return Array.isArray(p.type) ? p.type.join(' \\| ') : (p.type ?? 'unknown');
}

function table(schema: JsonSchema): string {
  const props = schema.properties ?? {};
  if (Object.keys(props).length === 0) return '_none_\n';
  const required = new Set(schema.required ?? []);
  const rows = Object.entries(props).map(([name, p]) => {
    const req = required.has(name)
      ? 'yes'
      : p.default !== undefined
        ? `default \`${JSON.stringify(p.default)}\``
        : 'no';
    return `| \`${name}\` | ${typeOf(p)} | ${req} | ${(p.description ?? '').replace(/\|/g, '\\|')} |`;
  });
  return ['| name | type | required | description |', '|---|---|---|---|', ...rows].join('\n') + '\n';
}

const parts: string[] = [
  '# Tool reference',
  '',
  '_Generated by `npm run docs:tools` from `src/tools/*.ts`. Do not edit by hand._',
  '',
  'Every tool returns a JSON body: `{ "ok": true, ...fields }` on success or',
  '`{ "ok": false, "code", "message", "recoverable", "details", "screenshot?" }` on failure (with `isError: true`).',
  'Error codes: ' +
    [
      'BROWSER_NOT_CONNECTED',
      'CHROME_LAUNCH_FAILED',
      'NOT_LOGGED_IN',
      'PROJECT_NOT_FOUND',
      'UI_NOT_FOUND',
      'REFERENCE_NOT_ATTACHED',
      'SEND_FAILED',
      'POLICY_BLOCKED',
      'APPROVAL_TIMEOUT',
      'GENERATION_TIMEOUT',
      'DOWNLOAD_FAILED',
      'SCENE_NOT_FOUND',
      'CLIP_NOT_FOUND',
      'MODEL_NOT_AVAILABLE',
      'BUSY',
      'INTERNAL',
    ]
      .map((c) => `\`${c}\``)
      .join(', ') +
    '.',
  '',
  '| tool | credits | summary |',
  '|---|---|---|',
  ...tools.map((t) => `| [\`${t.name}\`](#${t.name}) | ${t.annotations.destructiveHint ? 'yes' : 'no'} | ${t.title} |`),
  '',
];

for (const t of tools) {
  const input = z.toJSONSchema(z.object(t.input)) as JsonSchema;
  const output = z.toJSONSchema(z.object(t.output)) as JsonSchema;
  parts.push(
    `## ${t.name}`,
    '',
    t.description,
    '',
    `Annotations: ${
      Object.entries(t.annotations)
        .filter(([, v]) => v)
        .map(([k]) => `\`${k}\``)
        .join(', ') || '_none_'
    }`,
    '',
    '### Input',
    '',
    table(input),
    '### Output (plus `ok: true`)',
    '',
    table(output),
  );
}

const out = parts.join('\n');
const file = path.resolve('docs/tools.md');
if (process.argv.includes('--check')) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (current !== out) {
    process.stderr.write('docs/tools.md is stale; run `npm run docs:tools`\n');
    process.exit(1);
  }
  process.stderr.write('docs/tools.md is up to date\n');
} else {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out);
  process.stderr.write(`wrote ${file}\n`);
}
